name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          user: biosimulations   
          token: ${{ secrets.METRICS_TOKEN}}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_discussions: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_lines: yes
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://biosimulations.org
          plugin_people: yes
          plugin_repositories: yes
          plugin_traffic: yes
